spring:
  application:
    name: student-management

  datasource:
    url: jdbc:postgresql://localhost:5432/studentdb
    username: postgres
    password:

  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true

      #javax.persistence.schema-generation.create-source: metadata
      #javax.persistence.schema-generation.scripts.action: create
      #javax.persistence.schema-generation.scripts.create-target: create.sql


  flyway:
    baseline-on-migrate: true
    enabled: true
    username: postgres
    # password:
    baseline-description: "init"
    baseline-version: 0

